/**
 * Feature Map 09 — District Admin Command Center (MV-DAC)
 * Domain Models: All entity types, RBAC, engine inputs/outputs
 * Production-grade TypeScript with strict typing.
 */

// ─── Primitive Types ────────────────────────────────────────────────────────

export type FacilityType = 'PHC' | 'RH' | 'SDH' | 'DH' | 'CHC' | 'MC';
export type WardType = 'general' | 'icu' | 'maternity' | 'paediatric' | 'isolation' | 'emergency';
export type ResourceCategory = 'oxygen' | 'medicine' | 'blood' | 'equipment' | 'staff' | 'ppe';
export type StressLevel = 'normal' | 'moderate' | 'critical' | 'unknown';
export type AlertType = 'threshold' | 'forecast' | 'outbreak' | 'missing_report' | 'data_quality' | 'transfer';
export type AlertStatus = 'open' | 'acknowledged' | 'snoozed' | 'resolved';
export type AlertSeverity = 'info' | 'warning' | 'critical';
export type RequestType = 'transfer' | 'procurement' | 'escalation';
export type RequestStatus = 'draft' | 'submitted' | 'approved' | 'in_transit' | 'fulfilled' | 'rejected' | 'closed';
export type RequestUrgency = 'routine' | 'urgent' | 'emergency';
export type SeasonalPreset = 'standard' | 'monsoon_fevers' | 'dengue_peak' | 'respiratory_winter' | 'heatwave_summer';
export type SymptomCluster = 'acute_fever_rash' | 'acute_diarrhoeal' | 'sari' | 'jaundice' | 'encephalopathy' | 'cholera_like' | 'malaria_like';
export type AuditAction =
  | 'CREATE_RULE' | 'UPDATE_RULE' | 'DELETE_RULE'
  | 'APPROVE_TRANSFER' | 'REJECT_TRANSFER'
  | 'ACK_ALERT' | 'SNOOZE_ALERT' | 'RESOLVE_ALERT'
  | 'EXPORT_REPORT' | 'TRIGGER_REMINDER' | 'LOGIN' | 'INGEST_SNAPSHOT';

// ─── Core Entities ───────────────────────────────────────────────────────────

/**
 * A facility registered in the district command center.
 */
export interface CommandFacility {
  id: string;
  districtId: string;
  stateId: string;
  name: string;
  type: FacilityType;
  taluka: string;
  lat: number;
  lng: number;
  contactPerson: string;
  phone: string;
  email?: string;
  bedsTotal: number;
  bedsOccupied: number;
  icuTotal: number;
  icuOccupied: number;
  stressLevel: StressLevel;
  lastReportedAt: string;
  isStale: boolean;
  registeredAt: string;
}

/**
 * Timeseries snapshot of bed occupancy for a specific ward.
 */
export interface BedSnapshot {
  id: string;
  facilityId: string;
  districtId: string;
  timestamp: string;
  wardType: WardType;
  totalCapacity: number;
  occupied: number;
  free: number;
  occupancyRatePct: number;
  sourceUserId: string;
}

/**
 * Timeseries snapshot of a supply item or resource.
 */
export interface StockSnapshot {
  id: string;
  facilityId: string;
  districtId: string;
  timestamp: string;
  resourceId: string;
  resourceName: string;
  category: ResourceCategory;
  unit: string;
  currentQuantity: number;
  dailyUsageEst: number;
  daysOfCoverRemaining: number;
  sourceUserId: string;
}

/**
 * Configurable per-resource, per-facility threshold rule.
 */
export interface ThresholdRule {
  id: string;
  districtId: string;
  /** null = district-wide default */
  facilityId: string | null;
  resourceId: string;
  resourceName: string;
  wardType?: WardType | null;
  minimumLevel: number;
  reorderLevel: number;
  targetBuffer: number;
  daysOfCoverMin: number;
  severity: AlertSeverity;
  cooldownMinutes: number;
  seasonalPreset: SeasonalPreset;
  isActive: boolean;
  updatedBy: string;
  updatedAt: string;
}

/**
 * Aggregated syndromic surveillance counts per facility per day.
 * NOTE: NEVER contains patient-identifiable information.
 */
export interface SyndromicCount {
  id: string;
  date: string; // YYYY-MM-DD
  facilityId: string;
  districtId: string;
  symptomCluster: SymptomCluster;
  caseCount: number;
  reportedBy: string;
  reportedAt: string;
}

/**
 * A district-level command alert generated by any of the 4 engines.
 */
export interface CommandAlert {
  id: string;
  districtId: string;
  facilityId: string | null;
  facilityName: string | null;
  type: AlertType;
  severity: AlertSeverity;
  resourceId?: string;
  headline: string;
  summaryText: string;
  whyFlagged: string;
  suggestedAction?: string;
  status: AlertStatus;
  snoozeReason?: string;
  snoozeUntil?: string;
  createdAt: string;
  acknowledgedBy?: string;
  acknowledgedAt?: string;
  resolvedAt?: string;
  resolvedBy?: string;
  /** Deduplication hash to prevent duplicate alerts within cooldown window */
  dedupKey: string;
}

/**
 * A transfer or procurement workflow request.
 */
export interface CommandRequest {
  id: string;
  districtId: string;
  type: RequestType;
  fromFacilityId: string;
  fromFacilityName: string;
  toFacilityId: string;
  toFacilityName: string;
  resourceId: string;
  resourceName: string;
  quantityRequested: number;
  urgency: RequestUrgency;
  notes?: string;
  status: RequestStatus;
  statusTimeline: Array<{
    status: RequestStatus;
    timestamp: string;
    actor: string;
    notes?: string;
  }>;
  linkedAlertId?: string;
  createdBy: string;
  approvedBy?: string;
  createdAt: string;
  updatedAt: string;
}

/**
 * Immutable audit log entry for all district-level admin actions.
 */
export interface CommandAuditLog {
  id: string;
  timestamp: string;
  districtId: string;
  userId: string;
  userRole: string;
  action: AuditAction;
  entity: string;
  entityId: string;
  diffSummary: string;
  ipAddress?: string;
}

// ─── Engine Output Types ─────────────────────────────────────────────────────

/**
 * Output of the Shortage Forecast Engine.
 */
export interface StockoutForecast {
  facilityId: string;
  resourceId: string;
  resourceName: string;
  currentQuantity: number;
  dailyUsageEst: number;
  projectedStockoutDate: string | null; // ISO date or null if sufficient
  daysUntilStockout: number | null;
  forecastPoints: Array<{
    date: string;
    predicted: number;
    lower90: number;
    upper90: number;
  }>;
  confidence: number; // 0-1
  method: 'holt_winters' | 'wma' | 'linear';
  isCritical: boolean;
}

/**
 * Output of the Epidemic Early Warning Engine.
 */
export interface EarlyWarningResult {
  districtId: string;
  symptomCluster: SymptomCluster;
  analysisDate: string;
  baselineMean: number;
  baselineStd: number;
  currentCount: number;
  zScore: number;
  c1Triggered: boolean;
  c2Triggered: boolean;
  c3Triggered: boolean;
  cusumValue: number;
  cusumThresholdExceeded: boolean;
  spatialClusterFacilities: string[];
  overallSeverity: AlertSeverity;
  situationalBrief: string; // Gemini-generated plain language summary
  recommendedActions: string[];
}

/**
 * Output of the Transfer Recommender.
 */
export interface TransferRecommendation {
  fromFacilityId: string;
  fromFacilityName: string;
  surplusAvailable: number;
  distanceKm: number;
  estimatedTravelMinutes: number;
  score: number; // Composite ranking score
  remainingAfterTransfer: number;
  isViable: boolean;
}

// ─── API Response / Aggregate Types ─────────────────────────────────────────

/**
 * S1 District Overview: Aggregated KPIs for the entire district.
 */
export interface DistrictOverview {
  districtId: string;
  districtName: string;
  stateName: string;
  totalFacilities: number;
  facilitiesReporting: number;
  missingReportCount: number;
  totalBeds: number;
  availableBeds: number;
  availableBedsPercent: number;
  totalIcuBeds: number;
  availableIcuBeds: number;
  availableIcuPercent: number;
  criticalFacilities: string[];
  openAlerts: number;
  criticalAlerts: number;
  activeOutbreakClusters: number;
  oxygenShortageFacilities: string[];
  lastUpdated: string;
  stressDistribution: {
    normal: number;
    moderate: number;
    critical: number;
    unknown: number;
  };
}

/**
 * Reporting compliance matrix (used in S3 Reports tracker).
 */
export interface ReportingMatrix {
  districtId: string;
  dates: string[]; // Last N days
  facilities: Array<{
    facilityId: string;
    facilityName: string;
    type: FacilityType;
    reportedDates: string[];
    missingDates: string[];
    lastReportedAt: string | null;
    isStale: boolean;
    contactPhone: string;
  }>;
}

/**
 * Notification preference settings per user.
 */
export interface NotificationPreference {
  userId: string;
  districtId: string;
  criticalAlertPush: boolean;
  warningAlertPush: boolean;
  missingReportPush: boolean;
  outbreakAlertPush: boolean;
  quietHoursStart?: string; // HH:MM
  quietHoursEnd?: string;   // HH:MM
  emailRecipients: string[];
  smsFallbackNumbers: string[];
}
